[package]
name = "mauricefight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.20.0"
rand = "0.8.5"
queues = "1.0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
